import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import UseLenis from "./hooks/UseLenis";
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Theo Markin | freenlacer And desginer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <UseLenis>{children}</UseLenis>
      </body>
    </html>
  );
}
